"""
ChromaDB vector store wrapper.
Embeddings are generated by the dedicated ollama-embed container via the Ollama
/api/embeddings HTTP endpoint, keeping the app image lean and model serving uniform.
"""
import logging
from typing import Any, Optional

import chromadb
import httpx
from chromadb.config import Settings as ChromaSettings

from src.config import get_settings

logger = logging.getLogger(__name__)

EMBEDDING_MODEL_VERSION = "nomic-embed-text-v1.5"

_chroma_client: Optional[chromadb.PersistentClient] = None


def _embed_texts(texts: list[str]) -> list[list[float]]:
    """
    Embed a list of strings using the Ollama embedding container.
    Calls POST /api/embeddings once per text (Ollama does not batch in a single call).
    """
    settings = get_settings()
    url = f"{settings.ollama_embed_url}/api/embeddings"
    model = settings.embedding_model
    embeddings: list[list[float]] = []
    with httpx.Client(timeout=60.0) as client:
        for text in texts:
            try:
                resp = client.post(url, json={"model": model, "prompt": text})
                resp.raise_for_status()
                embeddings.append(resp.json()["embedding"])
            except httpx.HTTPStatusError as exc:
                logger.error("Ollama embed HTTP error for model %s: %s", model, exc)
                raise RuntimeError(f"Embedding request failed: {exc}") from exc
            except httpx.RequestError as exc:
                logger.error("Ollama embed connection error (%s): %s", url, exc)
                raise RuntimeError(f"Cannot reach embedding service at {url}") from exc
    return embeddings


def _get_client() -> chromadb.PersistentClient:
    global _chroma_client
    if _chroma_client is None:
        path = get_settings().chroma_db_path
        logger.info("Initialising ChromaDB at: %s", path)
        _chroma_client = chromadb.PersistentClient(
            path=path,
            settings=ChromaSettings(anonymized_telemetry=False),
        )
    return _chroma_client


def get_collection(name: Optional[str] = None) -> chromadb.Collection:
    """Return (or create) the named ChromaDB collection."""
    collection_name = name or get_settings().chroma_collection
    client = _get_client()
    return client.get_or_create_collection(
        name=collection_name,
        metadata={
            "hnsw:space": "cosine",
            "embedding_model_version": EMBEDDING_MODEL_VERSION,
        },
    )


def upsert_documents(
    documents: list[str],
    metadatas: list[dict[str, Any]],
    ids: list[str],
    collection_name: Optional[str] = None,
) -> None:
    """
    Embed and upsert a batch of documents into ChromaDB.

    Args:
        documents: List of raw text strings to embed.
        metadatas: Parallel list of metadata dicts (user_id, parent_asin, rating, …).
        ids: Parallel list of unique document IDs.
        collection_name: Override the default collection name.
    """
    embeddings = _embed_texts(documents)
    collection = get_collection(collection_name)
    collection.upsert(
        ids=ids,
        embeddings=embeddings,
        documents=documents,
        metadatas=metadatas,
    )
    logger.info("Upserted %d documents into collection '%s'", len(ids), collection.name)


def search(
    query: str,
    top_k: int = 10,
    where: Optional[dict] = None,
    collection_name: Optional[str] = None,
) -> list[dict[str, Any]]:
    """
    Semantic search over the ChromaDB collection.

    Args:
        query: Natural language query string.
        top_k: Number of results to return.
        where: Optional ChromaDB metadata filter dict, e.g. {"user_id": "U123"}.
        collection_name: Override the default collection name.

    Returns:
        List of result dicts with keys: id, document, similarity_score, and all metadata fields.
    """
    q_emb = _embed_texts([query])
    collection = get_collection(collection_name)

    kwargs: dict[str, Any] = {
        "query_embeddings": q_emb,
        "n_results": top_k,
        "include": ["documents", "metadatas", "distances"],
    }
    if where:
        kwargs["where"] = where

    try:
        results = collection.query(**kwargs)
    except Exception as exc:
        logger.error("ChromaDB query failed: %s", exc)
        return []

    output: list[dict[str, Any]] = []
    ids = results.get("ids", [[]])[0]
    docs = results.get("documents", [[]])[0]
    metas = results.get("metadatas", [[]])[0]
    dists = results.get("distances", [[]])[0]

    for doc_id, doc, meta, dist in zip(ids, docs, metas, dists):
        entry: dict[str, Any] = {"id": doc_id, "document": doc, "similarity_score": 1.0 - dist}
        entry.update(meta or {})
        output.append(entry)

    return output


def collection_count(collection_name: Optional[str] = None) -> int:
    """Return the number of documents in the collection."""
    return get_collection(collection_name).count()
